esphome:
  name: esphome-web-12a0bc
  friendly_name: ESPHome Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4oz/2D8ozEqzmHlr4yKMw2II3faBaEuA2/bKpAlFtdY="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-12A0Bc"
    password: "Qk8hM3kPX4Vj"

captive_portal:
# 8 CH Relay
switch:
  - platform: gpio
    name: "Switch 1"
    pin: 25

  - platform: gpio
    name: "Switch 2"
    pin: 26
    
  - platform: gpio
    name: "Switch 3"
    pin: 27
    
  - platform: gpio
    name: "Switch 4"
    pin: 14  

  - platform: gpio
    name: "Switch 5"
    pin: 12

  - platform: gpio
    name: "Switch 6"
    pin: 13

  - platform: gpio
    name: "Switch 7"
    pin: 15

  - platform: gpio
    name: "Switch 8"
    pin: 23
    
#Buzzer
  - platform: gpio
    name: "Buzzer"
    pin: 16
    inverted: true
    
# Example configuration entry
sensor:
  - platform: ultrasonic
    trigger_pin: 5
    echo_pin: 18
    name: "Ultrasonic Sensor"
    update_interval: 1s
    accuracy_decimals: 2

#MQ2 Methane Gas
  - platform: adc
    pin: 35
    name: "MQ2 CH4 sensor"
    accuracy_decimals: 0
    id: MQ2_CH4
    update_interval: 2s
    unit_of_measurement: "ppm"
    filters: 
    - lambda: return (pow(10, log10((0.12/x)*(5-x)/(5-0.12))/(-0.35))) ;


# LED
  - platform: adc
    pin: 36
    
    filters:
      - lambda: |-
          if (x > 3.15) {
            return 0;
          } else if (x < 1.30) {
            return 100;
          } else {
            return (3.15-x) / (3.15-1.30) * 100.0;
          }
    name: "ldr"
    unit_of_measurement: "%"
    update_interval: 2s
    attenuation: auto
    accuracy_decimals: 0
  
# Example configuration entry
spi:
  clk_pin: 22
  miso_pin: 17
  mosi_pin: 32

rc522_spi: # or rc522_i2c
  cs_pin: 21
  update_interval: 1s
binary_sensor :
  - platform: rc522
    uid: 93-57-2C-11
    name: "RFID Card"
